/**
 * Generated by "@vuepress/internal-routes"
 */

import {injectComponentOption, ensureAsyncComponentsLoaded} from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout
  from "/Users/lzz/Desktop/null-wheel/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-302f38c8",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-302f38c8").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-2413ea50",
    path: "/docs/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2413ea50").then(next)
    },
  },
  {
    path: "/docs/index.html",
    redirect: "/docs/"
  },
  {
    name: "v-97e011de",
    path: "/docs/components/button.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-97e011de").then(next)
    },
  },
  {
    name: "v-47208a8e",
    path: "/docs/components/tabs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-47208a8e").then(next)
    },
  },
  {
    name: "v-78ceb5aa",
    path: "/docs/get-start/start.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-78ceb5aa").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]
