/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "NULL UI",
  "description": "",
  "base": "/null-ui/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Null UI",
        "actionText": "快速上手 →",
        "actionLink": "/docs/get-start/start"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-302f38c8",
      "path": "/",
      "lastUpdated": "7/23/2020, 2:44:03 PM"
    },
    {
      "title": "NULL Vue",
      "frontmatter": {},
      "regularPath": "/docs/",
      "relativePath": "docs/README.md",
      "key": "v-2413ea50",
      "path": "/docs/",
      "headers": [
        {
          "level": 2,
          "title": "Components",
          "slug": "components"
        }
      ],
      "lastUpdated": "7/23/2020, 2:44:03 PM"
    },
    {
      "title": "快速上手",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "入",
        "7": "门"
      },
      "regularPath": "/docs/get-start/start.html",
      "relativePath": "docs/get-start/start.md",
      "key": "v-78ceb5aa",
      "path": "/docs/get-start/start.html",
      "lastUpdated": "7/23/2020, 2:44:03 PM"
    },
    {
      "title": "Switch",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "s",
        "7": "w",
        "8": "i",
        "9": "t",
        "10": "c",
        "11": "h"
      },
      "regularPath": "/docs/components/switch.html",
      "relativePath": "docs/components/switch.md",
      "key": "v-4fef080d",
      "path": "/docs/components/switch.html",
      "headers": [
        {
          "level": 2,
          "title": "基本用法",
          "slug": "基本用法"
        }
      ]
    },
    {
      "title": "Button 按钮",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "B",
        "7": "u",
        "8": "t",
        "9": "t",
        "10": "o",
        "11": "n"
      },
      "regularPath": "/docs/components/button.html",
      "relativePath": "docs/components/button.md",
      "key": "v-97e011de",
      "path": "/docs/components/button.html",
      "headers": [
        {
          "level": 2,
          "title": "基本用法",
          "slug": "基本用法"
        }
      ],
      "lastUpdated": "7/27/2020, 4:26:27 PM"
    },
    {
      "title": "Tabs",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "t",
        "7": "a",
        "8": "b",
        "9": "s"
      },
      "regularPath": "/docs/components/tabs.html",
      "relativePath": "docs/components/tabs.md",
      "key": "v-47208a8e",
      "path": "/docs/components/tabs.html",
      "headers": [
        {
          "level": 2,
          "title": "基本用法",
          "slug": "基本用法"
        }
      ],
      "lastUpdated": "7/27/2020, 4:26:27 PM"
    }
  ],
  "themeConfig": {
    "lastUpdated": "最后更新时间",
    "smoothScroll": true,
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "文档",
        "link": "/docs/"
      }
    ],
    "sidebar": {
      "/docs/": [
        "",
        {
          "title": "入门",
          "collapsable": false,
          "children": [
            "./get-start/start"
          ]
        },
        {
          "title": "基础组件",
          "collapsable": false,
          "children": [
            "./components/button",
            "./components/switch"
          ]
        },
        {
          "title": "数据展示",
          "collapsable": false,
          "children": [
            "./components/tabs"
          ]
        }
      ]
    }
  }
}